export const LAYOUT_CONSTANTS = {
    MOBILE_SIDEBAR_WIDTH: 40,
    DESKTOP_SIDEBAR_WIDTH_COLLAPSED: 40,
    DESKTOP_SIDEBAR_WIDTH_EXPANDED: 250,
    HEADER_HEIGHT: 40,
    FOOTER_MIN_HEIGHT: 32,
} as const;
